multiplayer_blog/urls.py
import xadmin
from django.contrib import admin
#from django.urls import path
from django.conf.urls import url
#from blog.views import post_list,post_detail
from django.urls import re_path
from django.views.static import serve
from multiplayer_blog.settings.base import MEDIA_ROOT
from blog.views import (
IndexView,CategoryView,TagView,
PostDetailView,SearchView,AuthorView
)
from config.views import LinkListView
from comment.views import CommentView
from django.contrib.sitemaps import views as sitemap_views
from blog.rss import LatestPostFeed
from blog.sitemap import PostSitemap
from .autocomplete import CategoryAutocomplete,TagAutocomplete
from django.conf import settings
from django.conf.urls import url,include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from blog.apis import PostViewSet,CategoryViewSet
from rest_framework.documentation import include_docs_urls
from django.views.decorators.cache import cache_page
#采用django-rest-framework提供的router更好的生成URL
router=DefaultRouter()
router.register(r'post',PostViewSet,base_name='api-post')

router.register(r'category',CategoryViewSet,base_name='api-category')

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^category/(?P<category_id>\d+)/$', CategoryView.as_view(), name='category-list'),
    url(r'^tag/(?P<tag_id>\d+)/$', TagView.as_view(), name='tag-list'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^comment/$', CommentView.as_view(), name='comment'),
    url(r'^author/(?P<owner_id>\d+)/$', AuthorView.as_view(), name='author'),
    url(r'^post/(?P<post_id>\d+).html$', PostDetailView.as_view(), name='post-detail'),
    url(r'^links/$', LinkListView.as_view(), name='links'),
    url(r'^admin/',xadmin.site.urls,name='xadmin'),
    url(r'^rss|feed/',LatestPostFeed(),name='rss'),
    url(r'^sitemap\.xml$', cache_page(60 * 20, key_prefix='sitemap_cache_')(sitemap_views.sitemap), {'sitemaps': {'posts': PostSitemap}}),
    url(r'^category-autocomplete/$',CategoryAutocomplete.as_view(),name='category-autocomplete'),
    url(r'^tag-autocomplete/$',TagAutocomplete.as_view(),name='tag-autocomplete'),
    url(r'^ckeditor/',include('ckeditor_uploader.urls')),
    url(r'^api/',include(router.urls)),
    re_path('media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    url(r'^api/docs/',include_docs_urls(title='gulang_blog apis')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)



#只有在DEBUG模式下才加载debug_toolbar模块
'''if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns'''

comment/models.py
from __future__ import unicode_literals
from blog.models import Post
from django.db import models


class Comment(models.Model):
    STATUS_NORMAL = 1
    STATUS_DELETE = 0
    STATUS_ITEMS = (
        (STATUS_NORMAL, '正常'),
        (STATUS_DELETE, '删除'),
    )
    target = models.CharField(max_length=100, verbose_name="评论目标")
    content = models.CharField(max_length=2000, verbose_name="内容")
    nickname = models.CharField(max_length=50, verbose_name="昵称")
    website = models.URLField(verbose_name="网站")
    email = models.EmailField(verbose_name="邮箱")
    status = models.PositiveIntegerField(default=STATUS_NORMAL, choices=STATUS_ITEMS, verbose_name="状态")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        verbose_name = verbose_name_plural = "评论"

    @classmethod
    def get_by_target(cls, target):
        return cls.objects.filter(target=target, status=cls.STATUS_NORMAL)

comment/forms.py
import mistune
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    nickname = forms.CharField(
        label='昵称',
        max_length=50,
        widget=forms.widgets.Input(
            attrs={'class': 'form-control', 'style': "width: 15%;"}
        )
    )
    email = forms.CharField(
        label='Email',
        max_length=50,
        widget=forms.widgets.EmailInput(
            attrs={'class': 'form-control', 'style': "width: 25%;"}
        )
    )
    website = forms.CharField(
        label='网站',
        max_length=100,
        widget=forms.widgets.URLInput(
            attrs={'class': 'form-control', 'style': "width: 30%;"}
        )
    )

    content = forms.CharField(
        label="内容",
        max_length=500,
        widget=forms.widgets.Textarea(
            attrs={'rows': 6, 'cols': 60, 'class': 'form-control','style': "width: 40%;"}
        )
    )

    def clean_content(self):
        content = self.cleaned_data.get('content')
        content = mistune.markdown(content)
        return content

    class Meta:
        model = Comment
        fields = ['nickname', 'email', 'website', 'content']

comment/views.py
from django.shortcuts import redirect
from django.views.generic import TemplateView
from .forms import CommentForm

# Create your views here.

class CommentView(TemplateView):
    http_method_names = ['post']
    template_name = 'comment/result.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST)
        target = request.POST.get('target')

        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.target = target
            instance.save()
            succeed = True
            return redirect(target)
        else:
            succeed = False

        context = {
            'succeed': succeed,
            'form': comment_form,
            'target': target,
        }
        return self.render_to_response(context)

multiplayer_blog/themes/bootstrap/templates/comment/block.html
{% load static %}

<button type="button" class="list-group-item list-group-item-action active"style="margin-bottom: 10px;background-color: dimgray;border-color: dimgray">
    评论列表
  </button>





    <form id="comment_form" class="form-group" action="/comment/" method="POST">
        {% csrf_token %}
        <input class="from-control " name="target" type="hidden" value="{{ target }}"/>
        {{ comment_form }}
        <div id="captcha_section"></div>
         <button id="submit" type="submit" class="btn btn-primary" value="提交" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">Submit</button>
    </form>







    <!-- 评论列表 -->




<div class="spinner-border spinner-border-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>
<div class="spinner-grow spinner-grow-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>

<div class="spinner-grow spinner-grow-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>

<div class="spinner-grow spinner-grow-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>
<div class="spinner-grow spinner-grow-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>
<div class="spinner-grow spinner-grow-sm" role="status">
  <span class="sr-only">Loading...</span>
</div>
    {% for comment in comment_list %}
        <button type="button" class="list-group-item list-group-item-action active"style="max-width: 600px;background-color: dimgray;border-color: dimgray">
            访客：<a href="{{ comment.website }}" style="color: white">{{ comment.nickname }}</a>
  </button>
  <a class="list-group-item list-group-item-action"style="max-width:600px">
    <div class="d-flex w-100 justify-content-between">
      <img src="{% static 'img/avatar.ico' %}" class="img-rounded card-img-top"style="max-height: 40px;max-width: 40px;margin-bottom:30px;margin-top: 5px;">
      <small>{{ comment.created_time }}</small>
    </div>

        {% autoescape off %}
            <!--字数超出一定限制后换行，避免行过长，超出整个页面-->
           <h5 style="white-space:normal; word-break:break-all;overflow:hidden;"> {{ comment.content }}</h5>
                {% endautoescape %}

    <p style="text-align: end"><small style="width: auto;">.......</small></p>
  </a>
    {% endfor %}


</div>

multiplayer_blog/themes/bootstrap/templates/comment/result.html
<!doctype html>
<html>
    <head>
        <title>评论结果页 - typeidea</title>
        <style>
        body {TEXT-ALIGN: center;}
        .result {
            text-align: center;
            width: 40%;
            margin: auto;
        }
        .errorlist {color: red;}
        ul li {
            list-style-type: None;
        }
        </style>
    </head>
    <body>
        <div class="result">
            {% if succeed %}
                评论成功！
                <a href="{{ target }}">返回</a>
            {% else %}
                <ul class="errorlist">
                {% for field, message in form.errors.items %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
                <a href="javascript:window.history.back();">返回</a>
            {% endif %}
        </div>
    </body>
</html>